image: node:18

pages:
  stage: deploy
  before_script:
    - echo "Configuring npm registry..."
    - npm config set registry https://registry.npmmirror.com
    - npm config get registry
    - npm install -g npm@9.9.2
    - npm --version
  script:
    - node --version
    - rm -f package-lock.json
    - npm install --legacy-peer-deps
    - npm run build
    - mv dist public
    - ls -la public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  cache:
    paths:
      - node_modules/
  only:
    - master
